### PR TITLE
feat: add openmage and adobe commerce

### PR DESCRIPTION
**Pull request by polillomm**

### CODE REVIEW

**Comment by polillomm** [comment]
The images for **OpenMage** and **Adobe Commerce** will be updated when hosted on **Speedia**.

For **Adobe Commerce**, need to install it and provide screenshots for hosting.

**Comment by polillomm** [comment]
To install **Adobe Commerce** in its current LTS version (`2.4.7-p2`), it was necessary to remove **OpenSearch** authentication from the **Adobe Commerce** manifest. **Adobe Commerce** cannot handle connections to search engines with authentication and does not work with **Elasticsearch 8**, as noted in this GitHub Issue: https://github.com/magento/magento2/issues/37236.

The workaround was to disable authentication and restart the service, which allowed the installation to proceed.

Additionally, static resources are not being found. There doesn't seem to be an issue with the `.htaccess` file, as the **Adobe Commerce** files are located in the `/pub` directory and the `.htaccess` in the root directory redirects to these files. However, static files are not working and need to be fixed.

**Comment by polillomm** [comment]
It was necessary to adjust the proxy buffer size settings because **Adobe Commerce** requires more than the default **NGINX** values. This requirement is not documented in their installation instructions or recommended settings, so this note provides a hint for making it work.

**Comment by polillomm** [comment]
Static resources are not being found. There doesn't seem to be an issue with the `.htaccess` file, as the **Adobe Commerce** files are located in the `/pub` directory and the `.htaccess` in the root directory redirects to these files. However, static files are not working and need to be fixed.

**Comment by polillomm** [comment]
<h3>IMPORTANT</h3>

To complete the installation, **Adobe** requires you to specify the edition you want to install and provide the appropriate credentials.

The available editions are `community`, which is the open-source version, and `enterprise`, which is the paid version.

To obtain the necessary credentials, follow these steps: https://experienceleague.adobe.com/en/docs/commerce-operations/installation-guide/prerequisites/authentication-keys.

**Comment by polillomm** [comment]
@ntorga 
Static resources are not being found. There doesn't seem to be an issue with the `.htaccess` file, as the **Adobe Commerce** files are located in the `/pub` directory and the `.htaccess` in the root directory redirects to these files. However, static files are not working and need to be fixed.

**Comment by ntorga** [comment]
Alright, gonna merge and fix all the pending issues on a new branch.

**Pull request merged**
